#!/bin/sh

res=0

while read oldrev newrev refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    if [ "develop" = "$branch" ]
	then
        WDIR="${PWD}"
		cd $(dirname "$0")/../..
		
		if [ -f .sync ]
		then
			echo "Already synchronizing"
			res=1
		fi
		
		cd "$WDIR"
    fi
done

exit $res